# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb962509ea42290671e516a0771eeb3e5576e6d8e04457393633afce7ebadef8a90780381d4041395595f15b22c980c8e21daf17b778044b1b39eff90d995af

test:
  secret_key_base: a26283a2609ebf3ba8d7d98dadc327042f8a4ba48cc89bc32343282f6fa6cfbfdd2c26638863e76edcb6318f6eff2e824c2eb047aecc7bf7e99aa0049d728873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
